#!/usr/bin/env bash
# Process and PID file

touch /var/run/myscript.pid
data=$(pgrep -f /var/run/myscript.pid) 
$data >> /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	trap "echo I hate the kill command" SIGTERM
	trap "echo Y U no love me?!" SIGINT
	trap "rm /var/run/myscript.pid" SIGQUIT SIGTERM
	trap "break" SIGQUIT SIGTERM
done
