#!/usr/bin/env bash
# Manage my process

start() {
	./manage_my_process &
	echo $! >> /var/run/my_process.pid
}

stop() {
	pkill -9 -f ./manage_my_process
	rm /var/run/my_process.pid
}	

restart() {
	stop
	start
	echo "manage_my_process restarted"
}	

case "$1" in 
	start)
		start
		echo "manage_my_process started"
		;;
	stop)
		stop
		echo "manage_my_process stopped"
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac
