#!/usr/bin/env bash
# Manage my process

if [[ $1 == "start"  ]]
then
	./manage_my_process
	touch /var/run/my_process.pid
	data=$(pgrep -f manage_my_process)
        $data >> /var/run/my_process.pid	
	echo "manage_my_process started"
elif [[ $1 == "stop" ]]
then
	pkill -9 -f manage_my_process
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [[ $1 == "restart" ]]
then
	pkill -9 -f manage_my_process
	rm /var/run/my_process.pid
	./manage_my_process
	pgrep -f manage_my_process >> /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
